language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - sudo apt-get install python3-tk
        - pwd

      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - DISPLAY=:99.0
      
install: 
  - pip3 install --upgrade pip

script: 
  - gsctl -l 1000 -w 800 -g 10
