language: python            # this works for Linux but is an error on macOS or Windows
services:
  - xvfb
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - sudo apt-get install python3-tk
        - sudo python setup.py install

      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      
install: 
  - pip3 install --upgrade pip

script: 
  - cd gs/test
  - python gs_test.py
